### ISSUE TITLE
fetch token doesn't work

### ISSUE THREAD

**Issue by tobwen** [philipperemy/Deep-Learning-Tinder#3]
I'm getting this when running main.py: `werkzeug.exceptions.BadRequestKeyError: 400: Bad Request`
What details do you need to get it fixed?

**Comment by philipperemy** [comment]
Can you copy and paste this in your browser and see if you're prompted with a popup:

`You have already authorized Tinder`

You must be connected to Facebook prior hand (in your browser just log in Facebook if not already done)

https://www.facebook.com/v2.6/dialog/oauth?redirect_uri=fb464891386855067%3A%2F%2Fauthorize%2F&display=touch&state=%7B%22challenge%22%3A%22IUUkEUqIGud332lfu%252BMJ    hxL4Wlc%253D%22%2C%220_auth_logger_id%22%3A%2230F06532-A1B9-4B10-BB28-B29956C71AB1%22%2C%22com.facebook.sdk_client_state%22%3Atrue%2C%223_method%22%3A%22sfvc_auth%22%7D&scope    =user_birthday%2Cuser_photos%2Cuser_education_history%2Cemail%2Cuser_relationship_details%2Cuser_friends%2Cuser_work_history%2Cuser_likes&response_type=token%2Csigned_request    &default_audience=friends&return_scopes=true&auth_type=rerequest&client_id=464891386855067&ret=login&sdk=ios&logger_id=30F06532-A1B9-4B10-BB28-B29956C71AB1&ext=1470840777&has    h=AeZqkIcf-NEW6vBd

**Comment by tobwen** [comment]
Yep, I'm getting "Du hast Tinder bereits autorisiert.", which is the German translation for "You have already authorized Tinder." :)

**Comment by philipperemy** [comment]
@tobwen we're going to try to manually fetch the `FB_AUTH_TOKEN`.

Can you follow the steps indicated here: https://gist.github.com/rtt/10403467#gistcomment-1846343 and see if works?

When you have it, please input it directly into the source code and skip the auto fetching part.

Let me know :)

PS: Might also be because your Facebook is not in english but I doubt about it.

**Comment by tobwen** [comment]
> When you have it, please input it directly into the source code and skip the auto fetching part.

Yep, the manual way works. Hmm, let us try to fix auto-fetching on weekend. Maybe a header value is needed.

**Comment by philipperemy** [comment]
Ok! Great to know that the manual way at least works! Sure thing, it should not be too difficult to debug it and see what it does not work for you.

**Comment by philipperemy** [comment]
@tobwen any news?
