### ISSUE TITLE
Select your own best pictures

### ISSUE THREAD

**Issue by soufiane8096** [philipperemy/Deep-Learning-Tinder#4]
Hey,

I really appreciate your work ! Congralutation ! 

I would like to know if there is an issue to select your best picture to make your profil attractive ?

**Comment by philipperemy** [comment]
Thanks a lot for this feedback!

Have a look at this article, you will love it: http://karpathy.github.io/2015/10/25/selfie/

It will answer your question :)

**Comment by soufiane8096** [comment]
Thank your for your answer. The Twitter bot is not working. Do you have another tool to "rate" selfies ?

**Comment by philipperemy** [comment]
@soufiane8096 I'm not aware of any tools. I think you'll have to make your own model.

Try to scrape data on Instagram with the number of likes related to the number of followers, and use NVIDIA DIGITS with exactly the same methodology like the one @karpathy and I used (in Deep Learning Tinder)
